### ISSUE TITLE
repository description doesn't make sense

### ISSUE THREAD

**Issue by mr-c** [cyverse-archive/de-webapp#1]
What does "Discovery Environment web application that propers the user interface for the overall distributed system" mean?

**Comment by tedgin** [comment]
Please substitute "propers" with "provides".  The Discovery Environment web application is the front end for the Discovery Environment.  It is one of our products at iPlant Collaborative, http://www.iplantcollaborative.org/discover/discovery-environment.  I'll fix the typo.  Thanks for finding it.
